include ~/.config/kitty/theme.conf

font_family                 CaskaydiaCove Nerd Font Mono
font_size                   15
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
mouse_hide_wait             2.0
cursor_shape                block
confirm_os_window_close     0
background_opacity          0.90
window_padding_width        8
enable_audio_bell           no

map ctrl+c                  copy_to_clipboard
map ctrl+v                  paste_from_clipboard
map ctrl+shift+c            send_text all \x03

map ctrl+Cyrillic_es        copy_to_clipboard
map ctrl+shift+Cyrillic_es  send_text all \x03
map ctrl+Cyrillic_em        paste_from_clipboard
