#!/usr/bin/env bash

DIR="$HOME/.config"
RASI="$DIR/rofi/powermenu.rasi"
CNFR="$DIR/rofi/confirm.rasi"

prompt="`hostname`"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
    option_1=" Lock"
    option_2="↺ Reboot"
    option_3=" Shutdown"
else
    option_1=""
    option_2="↺"
    option_3=""
fi
cnflayout=`cat ${CNFR} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$cnflayout" == 'NO' ]]; then
    yes=' Yes'
    no=' No'
else
    yes=''
    no=''
fi

rofi_cmd() {
    rofi -dmenu \
    -p "$prompt" \
    -mesg "$mesg" \
    -markup-rows \
    -theme ${RASI}
}

run_rofi() {
    echo -e "$option_1\n$option_2\n$option_3" | rofi_cmd
}

confirm_cmd() {
    rofi -dmenu \
    -p 'Confirmation' \
    -mesg 'Are you sure?' \
    -theme ${CNFR}
}

confirm_exit() {
    echo -e "$yes\n$no" | confirm_cmd
}

confirm_run () {
    selected="$(confirm_exit)"
    if [[ "$selected" == "$yes" ]]; then
        ${1} && ${2} && ${3}
    else
        exit
    fi
}

run_cmd() {
    if [[ "$1" == '--opt1' ]]; then
        loginctl lock-sessions
        elif [[ "$1" == '--opt2' ]]; then
        confirm_run 'systemctl reboot'
        elif [[ "$1" == '--opt3' ]]; then
        confirm_run 'systemctl poweroff'
    fi
}

chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
        run_cmd --opt1
    ;;
    $option_2)
        run_cmd --opt2
    ;;
    $option_3)
        run_cmd --opt3
    ;;
esac
